name: news_app
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  cached_network_image: null
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: null
  http: null
  sizer: null
  webview_flutter: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
