name: news_app
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  flame_svg: ^1.8.7
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_offline: ^3.0.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  http: null
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  svg_flutter: ^0.0.1
  webview_flutter: null

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
  generate: true

flutter:

  uses-material-design: true
  assets:
    - images/
